theme: jekyll-theme-cayman
title: Material for the 3MC Course on Epidemiological Modelling
description: Html versions of the slides for the course.
google_analytics: UA-1943806-8
google_site_verification: zrOU6pP7sLlXf7f0kW-NZRV1lZtdpybCfrJ3BeBMHQM
